parameters:
    api.registry.endpoint:  ~

services:
    api.registry:
        class: ApiBundle\Registry\RegistryApi
        arguments: [ '%api.registry.endpoint%' ]

    api.dispatcher:
        class: ApiBundle\Dispatcher\DispatcherManager

